services:
  gateway:
    depends_on:
      - auth-service
    build:
      context: gateway
      dockerfile: dockerfile
    restart: always
    ports:
      - "5138:8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  auth-service:
    volumes:
      - ./auth-service/internal/certs:/root/certs
      - ./auth-service/public:/root/public
    build:
      context: auth-service
      dockerfile: dockerfile
    restart: always
    env_file:
      - auth-service/.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  bridge-service:
    build:
      context: bridge-service
      dockerfile: dockerfile
    restart: always
    env_file:
      - bridge-service/.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  peer-service:
    build:
      context: peer-service
      dockerfile: dockerfile
    restart: always
    env_file:
      - peer-service/.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  mailing-service:
    build:
      context: mailing-service
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./mailing-service/.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  streaming-service:
    build:
      context: streaming-service
      dockerfile: dockerfile
    restart: always
    env_file:
      - streaming-service/.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  resource-service:
    image: dagm123/resource-service:1.4.4
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8090;http://0.0.0.0:7027;"
    depends_on:
      - rabbitmq
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - back-tier

  cache:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - back-tier

  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: "strongpassword"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    networks:
      - back-tier

volumes:
  rabbitmq_data:
  redis_data:

networks:
  back-tier:
    driver: bridge
